### ISSUE TITLE
Add flame graph

### ISSUE THREAD

**Issue by Jecvay** [lucko/spark-viewer#17]
[example](http://www.brendangregg.com/FlameGraphs/cpu-mysql-updated.svg)

Flame Graph is really fashionable in profile, and is really useful.

**Comment by DarkArc** [comment]
It's a wee-bit upside down, but I care far less about that :)

**Comment by lucko** [comment]
This has now been implemented and deployed to production :)

To open the flame view, just right click one of the nodes in the tree and click "View as flame graph"
