### ISSUE TITLE
Remember Mappings Option

### ISSUE THREAD

**Issue by PaulBGD** [lucko/spark-viewer#18]
With the new auto detect mappings, it'd be great if it was stored in localStorage somewhere that it was switched to No Mappings. While I think the auto detect is cool, I think if someone toggled it off then they likely don't want to use mappings every time (me personally.)

**Comment by PaulBGD** [comment]
Hmm another thing I noticed is it freezes up my entire browser (chromium) for around 10s when loading a large spark. Either mappings should be done via a worker or maybe rethink the auto-detect.

**Comment by lucko** [comment]
Storing mappings preference is a good idea - will look into that, thanks!

Could you send a link to the profile that takes too long to load?

I think what's probably happened is I've messed up the promise handling so it's blocking while the mappings data is loaded

**Comment by PaulBGD** [comment]
Pretty much any profile, although it acted kind of strange. It seemed the first time I loaded the profile it would lag, but then after it'd be fine when I reloaded. Looking at a new profile would cause it again.

**Comment by lucko** [comment]
The slow profile loading issue should be fixed by a3d7a205b0c0a81fa1ad1cacc098ff8b2b1605cc :)

**Comment by PaulBGD** [comment]
Turning off mappings seems to no longer work.

**Comment by lucko** [comment]
https://github.com/lucko/spark-viewer/commit/cab85dea57e4029cab52133f39363b638dc868b3

**Comment by lucko** [comment]
Implemented saving of mappings preference: e41dfa02c13e570a5a7d5cd5f68ad0495f990257
