### ISSUE TITLE
[Feature] Display self method time

### ISSUE THREAD

**Issue by KR33PY** [lucko/spark-viewer#20]
I often lack the ability to quickly view the time consumed not by method's children, but by the method itself.
For example, here's the `invoke` method, which consumes 0.03% of total cpu time, but I had to calculate that myself subtracting its children:
![pct](https://user-images.githubusercontent.com/75280223/111480652-454a7c00-8743-11eb-9332-5d94c4c488e2.png)

**Comment by lucko** [comment]
![Screenshot 2021-03-17 at 15 12 42](https://user-images.githubusercontent.com/8352868/111490847-42e02600-8733-11eb-9e98-8ad801f51913.png)

I've added this info in the hover details :)

**Comment by lucko** [comment]
dfd74a0fe24fcc866ecbed632ded71db8af1ba53
