### ISSUE TITLE
[Suggestion] Load and remap .nps files

### ISSUE THREAD

**Issue by Eufranio** [lucko/spark-viewer#24]
I have some `.nps` files taken from stall reports. It would be cool if the spark viewer was able to load and show those, and remap the method names with the appropriate versions. Is that possible?

**Comment by lucko** [comment]
Could you share an example file? :)

**Comment by Eufranio** [comment]
[spike-1044-2248395406.zip](https://github.com/lucko/spark-viewer/files/6865844/spike-1044-2248395406.zip)

**Comment by Eufranio** [comment]
Sampler mod: https://www.curseforge.com/minecraft/mc-mods/sampler

**Comment by lucko** [comment]
Unfortunately the mod is obfuscated, and the binary file isn't particularly readable.

Without a lot of work, it's not going to be possible - sorry!
