### ISSUE TITLE
Average time per tick instead of total time

### ISSUE THREAD

**Issue by kmecpp** [lucko/spark-viewer#26]
Instead of total time is it possible to show average time per tick? Time per tick would much more useful since it allows you to get an intuitive sense of how much time something is taking as opposed to total time which (assuming you know the duration of the profile and individual percent) doesn't really tell you anything new.

![image](https://user-images.githubusercontent.com/6520738/142075964-d476a118-c72e-4a3d-afee-299b5c763508.png)

**Comment by lucko** [comment]
Implemented in 2ab008786faf3eafe1f471b95baee1b0ddbd846b

![Screenshot 2022-06-26 at 20 37 41](https://user-images.githubusercontent.com/8352868/175831437-78a81cba-e56a-4ae3-bcc4-1831dfc242d6.png)

cc @electronicboy
