### ISSUE TITLE
Search bar for heapsummary's

### ISSUE THREAD

**Issue by voodootje0** [lucko/spark-viewer#33]

**Comment by montlikadani** [comment]
That's what I thought, but I would only implement this option for the `Type` column. So it only searches the type for the text you entered.

**Comment by aerulion** [comment]
I agree that would be very helpful. Previously, it was possible to search the entire heapsummary using Ctrl + F (at least when using Chrome), but unfortunately that does not work anymore as it now only searches the currently visible portion of the list.

**Comment by lucko** [comment]
:)
