### ISSUE TITLE
Add Dockerfile

### ISSUE THREAD

**Issue by Fukutu** [lucko/spark-viewer#36]
It would be very helpful if a project Dockerfile were made available

**Comment by lucko** [comment]
Perhaps - spark-viewer is a SPA, so hosting using a PaaS service like Vercel, Netlify or Cloudflare Pages is recommended.

**Comment by lucko** [comment]
I needed this for something else, so here you go: https://github.com/lucko/spark-viewer/pkgs/container/spark-viewer

It listens on port 3000 inside the container. :)
