### ISSUE TITLE
Return profiler data as json for external manipulation

### ISSUE THREAD

**Issue by DennieDev** [lucko/spark-viewer#42]
I'd love for us to have an api where we can give the profiler ID or be able to scrape the ?raw=1 url to get the content. 

My personal use-case: I want to scrape the content of: https://spark.lucko.me/[ID]?raw=1 and convert this data to a json object within PHP. However scraping the website doesn't work since the content isn't loaded directly (I'm guessing). And there is no PHP support to read the protobuff file that I know off.

**Comment by lucko** [comment]
The raw data is now returned directly instead of being rendered in the browser.

https://github.com/lucko/spark2json
7ff0a58416daefc019331dd2fb615cf981fa849f
02d118b1bc01060ed40cccadfc71e000b0bbb0ea
